version: "3.4"
services:
    # nopcommerce_web:
    #     build: .
    #     container_name: nopcommerce
    #     ports:
    #         - "80:80"
    #     depends_on:
    #         - nopcommerce_database
    nopcommerce_database:
        image: "postgres:latest"
        ports:
            - 5432:5432
        container_name: nopcommerce_postgres_server
        restart: "always"
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_DB: example
            POSTGRES_USER: example

volumes:
    nopcommerce_data:
